### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by kopsti** [codechavez/angular-inline-editor#1]
Adding module with:

```
import {InputEditorModule} from 'angular-inline-editor';

@NgModule({
  imports: [
    InputEditorModule.forRoot()
  ]
})
```

causes this error, because of 'forRoot'
```
ERROR in Error during template compile of 'AppModule'
Function calls are not supported in decorators but 'InputEditorModule' was called.
```

**Comment by codechavez** [comment]
Hi Kopsti,

Thank for being the first on reporting a bug we were waiting for it. 

Can you please provide us with a copy of your tsconfig, system or webpack config as well. So we can reproduce this issue with your settings.

Thank you.

**Comment by codechavez** [comment]
@kopsti

**Comment by codechavez** [comment]
@kopsti , We are unable to reproduce this issue. Can you provide more information about your environment and configurations?

**Comment by kopsti** [comment]
This is my package.json file, what else would you like me to send?
```
{
  "name": "client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.3",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-inline-editors": "^1.0.0",
    "core-js": "^2.4.1",
    "ngx-cookie-service": "^1.0.10",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by codechavez** [comment]
@kopsti have you tried to upgrade @anguler/cli to the latest version, which at this moment would be 1.7.1? Also can you provide us with your tsconfig.json file?

**Comment by kopsti** [comment]
@codechavez Updating to 1.7.1 didn't help. I paste my tsconfig.json file below:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by codechavez** [comment]
@kopsti We have tested our code with the configurations you provided us and we were unable to reproduce this issue, however we thank to you for reporting what you are experience because we found a dependency issue that we were able to removed. Please make sure you using our latest version with at me moment of this post is 1.0.1. Finally we recommend you to upgrade to the most latest version of Nodejs. 

Thank you for using angular-inline-editors

**Comment by kopsti** [comment]
@codechavez 
angular-cli: 1.7.1, node 9.6.1, angular 5.2.6 and version 1.0.1 of your package didn't work for me.
Thanks.
