### ISSUE TITLE
Function calls are not supported in decorators but 'InputEditorModule' was called.

### ISSUE THREAD

**Issue by ysiddiqui** [codechavez/angular-inline-editor#3]
Integrated in my project and it is working like a charm but when I'm generating build for production using `ng build --prod` it is showing me following error,

```
"ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'InputEditorModule' was called."
```

I tried every possible way I know and search on stackoverflow, but unfortunately no success.

**Comment by ProgzillaRadio** [comment]
Am having exactly the same issue.

**Comment by Kozyrov** [comment]
Another instance to bring this up to date. A development build in this case:

> ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'InputEditorModule' was called.

>node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare 
  block-scoped variable 'ngDevMode'.

>node_modules/angular-inline- 
 editors/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot 
  redeclare block-scoped variable 'ngDevMode'.
